//------------------------------------------------------------------------------

// <auto-generated>

//     This code was generated by a tool.

//

//     Changes to this file may cause incorrect behavior and will be lost if

//     the code is regenerated. 

// </auto-generated>

//------------------------------------------------------------------------------



namespace WPApplication {

    

    

    public partial class Default {

        

        /// <summary>

        /// form1 control.

        /// </summary>

        /// <remarks>

        /// Auto-generated field.

        /// To modify move field declaration from designer file to code-behind file.

        /// </remarks>

        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        

        /// <summary>

        /// Label4 control.

        /// </summary>

        /// <remarks>

        /// Auto-generated field.

        /// To modify move field declaration from designer file to code-behind file.

        /// </remarks>

        protected global::System.Web.UI.WebControls.Label Label4;

        

        /// <summary>

        /// Label1 control.

        /// </summary>

        /// <remarks>

        /// Auto-generated field.

        /// To modify move field declaration from designer file to code-behind file.

        /// </remarks>

        protected global::System.Web.UI.WebControls.Label Label1;

        

        /// <summary>

        /// TextBox1 control.

        /// </summary>

        /// <remarks>

        /// Auto-generated field.

        /// To modify move field declaration from designer file to code-behind file.

        /// </remarks>

        protected global::System.Web.UI.WebControls.TextBox TextBox1;

        

        /// <summary>

        /// RequiredFieldValidator1 control.

        /// </summary>

        /// <remarks>

        /// Auto-generated field.

        /// To modify move field declaration from designer file to code-behind file.

        /// </remarks>

        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;

        

        /// <summary>

        /// Label2 control.

        /// </summary>

        /// <remarks>

        /// Auto-generated field.

        /// To modify move field declaration from designer file to code-behind file.

        /// </remarks>

        protected global::System.Web.UI.WebControls.Label Label2;

        

        /// <summary>

        /// TextBox2 control.

        /// </summary>

        /// <remarks>

        /// Auto-generated field.

        /// To modify move field declaration from designer file to code-behind file.

        /// </remarks>

        protected global::System.Web.UI.WebControls.TextBox TextBox2;

        

        /// <summary>

        /// RequiredFieldValidator2 control.

        /// </summary>

        /// <remarks>

        /// Auto-generated field.

        /// To modify move field declaration from designer file to code-behind file.

        /// </remarks>

        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;

        

        /// <summary>

        /// DropDownList1 control.

        /// </summary>

        /// <remarks>

        /// Auto-generated field.

        /// To modify move field declaration from designer file to code-behind file.

        /// </remarks>

        protected global::System.Web.UI.WebControls.DropDownList DropDownList1;

        

        /// <summary>

        /// RequiredFieldValidator3 control.

        /// </summary>

        /// <remarks>

        /// Auto-generated field.

        /// To modify move field declaration from designer file to code-behind file.

        /// </remarks>

        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator3;

        

        /// <summary>

        /// RadioButtonList1 control.

        /// </summary>

        /// <remarks>

        /// Auto-generated field.

        /// To modify move field declaration from designer file to code-behind file.

        /// </remarks>

        protected global::System.Web.UI.WebControls.RadioButtonList RadioButtonList1;

        

        /// <summary>

        /// RequiredFieldValidator4 control.

        /// </summary>

        /// <remarks>

        /// Auto-generated field.

        /// To modify move field declaration from designer file to code-behind file.

        /// </remarks>

        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator4;

        

        /// <summary>

        /// CheckBoxList1 control.

        /// </summary>

        /// <remarks>

        /// Auto-generated field.

        /// To modify move field declaration from designer file to code-behind file.

        /// </remarks>

        protected global::System.Web.UI.WebControls.CheckBoxList CheckBoxList1;

        

        /// <summary>

        /// Button1 control.

        /// </summary>

        /// <remarks>

        /// Auto-generated field.

        /// To modify move field declaration from designer file to code-behind file.

        /// </remarks>

        protected global::System.Web.UI.WebControls.Button Button1;

        

        /// <summary>

        /// DatabaseInformation control.

        /// </summary>

        /// <remarks>

        /// Auto-generated field.

        /// To modify move field declaration from designer file to code-behind file.

        /// </remarks>

        protected global::System.Web.UI.WebControls.GridView DatabaseInformation;

        

        /// <summary>

        /// DataSource control.

        /// </summary>

        /// <remarks>

        /// Auto-generated field.

        /// To modify move field declaration from designer file to code-behind file.

        /// </remarks>

        protected global::System.Web.UI.WebControls.SqlDataSource DataSource;

    }

}

